scoreboard:
  name: 'yourserver'
  ts: 'ts.yourserver.de'
  online: '%online%/%max%'
Utils:
  compass: '§l§cSelector'
  hidestick: '§l§aPlayer Hider'
  showplayers: '§aShow Player'
  Hideplayers: '§cHide Player'
  showteammember: '§6Show Teammember'
  hubselector: '§bHubselector'
Permission:
  topic: '§7Your Rank :' 
  Player: 'lobby.player'
  name0: '§7Player' 
  Premium: 'lobby.Premium'
  name1: '➥ Premium' 
  Premium+: 'lobby.Premium+'
  name2: '➥ §6Premium§l§a+' 
  YouTuber: 'lobby.YouTuber'
  name3: '➥ §5YouTuber' 
  Builder: 'lobby.Builder'
  name4: '➥ §aBuilder' 
  Supporter: 'lobby.Sup'
  name5: '➥ §9Supporter' 
  Developer: 'lobby.Dev'
  name6: '➥ §1Developer' 
  Moderator: 'lobby.Mod'
  name7: '➥ §3Moderator' 
  Admin: 'lobby.Admin'
  name8: '➥ §cAdmin' 
  Owner: 'lobby.Owner'
  name9: '➥ §4Owner' 
Help:
  1: '--------------------[YourServer.Net]--------------------'
  2: 'Website : www.yourserver.net'
  3: 'TeamSpeak3 : ts.YourServer.net'
  4: 'Vote : Vote.yourserver.net'
  5: 'Shop : shop.yourserver.net'
  6: 'Twittwer : twitter.com'
  7: 'YouTube : youtube.com/yourserver.net'
  8: '--------------------[YourServer.Net]--------------------'